"""
Pinterest Analytics Setup Wizard
Interactive setup for easy configuration
"""

import os
import sys
from pathlib import Path

try:
    from rich.console import Console
    from rich.panel import Panel
    from rich.prompt import Prompt, Confirm
    from rich.table import Table
    RICH_AVAILABLE = True
except ImportError:
    RICH_AVAILABLE = False

console = Console() if RICH_AVAILABLE else None


def print_header():
    """Print setup wizard header"""
    if RICH_AVAILABLE:
        console.print(Panel.fit(
            "[bold red]Pinterest Analytics[/bold red]\n[dim]Setup Wizard[/dim]",
            border_style="red"
        ))
    else:
        print("\n" + "="*50)
        print("  Pinterest Analytics - Setup Wizard")
        print("="*50 + "\n")


def check_env_file() -> dict:
    """Check existing .env configuration"""
    env_path = Path('.env')
    config = {
        'PINTEREST_ACCESS_TOKEN': None,
        'PINTEREST_APP_ID': None,
        'PINTEREST_APP_SECRET': None,
    }
    
    if env_path.exists():
        with open(env_path, 'r') as f:
            for line in f:
                line = line.strip()
                if '=' in line and not line.startswith('#'):
                    key, value = line.split('=', 1)
                    key = key.strip()
                    value = value.strip().strip('"').strip("'")
                    if key in config and value:
                        config[key] = value
    
    return config


def save_env_file(config: dict):
    """Save configuration to .env file"""
    env_path = Path('.env')
    
    lines = []
    lines.append("# Pinterest Analytics Configuration")
    lines.append("# Generated by setup wizard")
    lines.append("")
    
    if config.get('PINTEREST_ACCESS_TOKEN'):
        lines.append(f"PINTEREST_ACCESS_TOKEN={config['PINTEREST_ACCESS_TOKEN']}")
    
    if config.get('PINTEREST_APP_ID'):
        lines.append(f"PINTEREST_APP_ID={config['PINTEREST_APP_ID']}")
    
    if config.get('PINTEREST_APP_SECRET'):
        lines.append(f"PINTEREST_APP_SECRET={config['PINTEREST_APP_SECRET']}")
    
    with open(env_path, 'w') as f:
        f.write('\n'.join(lines) + '\n')
    
    return env_path


def get_input(prompt: str, default: str = None, password: bool = False) -> str:
    """Get user input with optional default"""
    if RICH_AVAILABLE:
        return Prompt.ask(prompt, default=default or "", password=password)
    else:
        if default:
            prompt = f"{prompt} [{default}]"
        value = input(f"{prompt}: ")
        return value if value else (default or "")


def confirm(prompt: str, default: bool = True) -> bool:
    """Get yes/no confirmation"""
    if RICH_AVAILABLE:
        return Confirm.ask(prompt, default=default)
    else:
        response = input(f"{prompt} [{'Y/n' if default else 'y/N'}]: ").strip().lower()
        if not response:
            return default
        return response in ('y', 'yes')


def print_step(step: int, total: int, message: str):
    """Print step indicator"""
    if RICH_AVAILABLE:
        console.print(f"\n[bold cyan]Step {step}/{total}:[/bold cyan] {message}")
    else:
        print(f"\n[Step {step}/{total}] {message}")


def print_success(message: str):
    """Print success message"""
    if RICH_AVAILABLE:
        console.print(f"[green]✓[/green] {message}")
    else:
        print(f"[OK] {message}")


def print_warning(message: str):
    """Print warning message"""
    if RICH_AVAILABLE:
        console.print(f"[yellow]![/yellow] {message}")
    else:
        print(f"[!] {message}")


def print_error(message: str):
    """Print error message"""
    if RICH_AVAILABLE:
        console.print(f"[red]✗[/red] {message}")
    else:
        print(f"[ERROR] {message}")


def run_setup_wizard():
    """Run the interactive setup wizard"""
    print_header()
    
    # Check current configuration
    current_config = check_env_file()
    has_token = bool(current_config.get('PINTEREST_ACCESS_TOKEN'))
    has_app = bool(current_config.get('PINTEREST_APP_ID'))
    
    if has_token:
        print_success("Access token found in .env")
        if not confirm("Do you want to reconfigure?", default=False):
            print("\nSetup complete! Run: python main.py test")
            return
    
    # Step 1: Introduction
    print_step(1, 4, "Pinterest Developer App")
    
    if RICH_AVAILABLE:
        console.print("""
To use Pinterest Analytics, you need:

1. [bold]Pinterest Developer App[/bold]
   → Go to: [link]https://developers.pinterest.com/apps/[/link]
   → Click "Create app"
   → Fill in app details:
     • App name: Pinterest Analytics
     • Description: Personal analytics tool
     • Website URL: https://github.com/xodapi/pin
     • Privacy Policy: https://github.com/xodapi/pin/blob/main/PRIVACY.md

2. [bold]Get your credentials[/bold]
   → After approval, copy App ID and App Secret
""")
    else:
        print("""
To use Pinterest Analytics, you need:

1. Pinterest Developer App
   → Go to: https://developers.pinterest.com/apps/
   → Click "Create app"
   
2. Get your credentials
   → After approval, copy App ID and App Secret
""")
    
    if not confirm("Have you created a Pinterest Developer App?"):
        print("\nPlease create an app first:")
        print("  https://developers.pinterest.com/apps/")
        print("\nThen run: python setup.py")
        return
    
    # Step 2: App credentials
    print_step(2, 4, "Enter App Credentials")
    
    app_id = get_input(
        "App ID",
        default=current_config.get('PINTEREST_APP_ID', '')
    )
    
    app_secret = get_input(
        "App Secret",
        default=current_config.get('PINTEREST_APP_SECRET', ''),
        password=True
    )
    
    # Step 3: Access Token
    print_step(3, 4, "Access Token")
    
    if RICH_AVAILABLE:
        console.print("""
[bold]Option A:[/bold] If you have an access token, enter it now
[bold]Option B:[/bold] Leave empty to generate one using OAuth
""")
    else:
        print("\nOption A: Enter existing access token")
        print("Option B: Leave empty to generate via OAuth")
    
    access_token = get_input(
        "Access Token (or leave empty)",
        default=current_config.get('PINTEREST_ACCESS_TOKEN', ''),
        password=True
    )
    
    # Step 4: Save configuration
    print_step(4, 4, "Save Configuration")
    
    new_config = {
        'PINTEREST_APP_ID': app_id,
        'PINTEREST_APP_SECRET': app_secret,
        'PINTEREST_ACCESS_TOKEN': access_token,
    }
    
    # Show summary
    if RICH_AVAILABLE:
        table = Table(title="Configuration Summary")
        table.add_column("Setting", style="cyan")
        table.add_column("Value")
        table.add_row("App ID", app_id[:10] + "..." if app_id else "[red]Not set[/red]")
        table.add_row("App Secret", "****" if app_secret else "[red]Not set[/red]")
        table.add_row("Access Token", "****" if access_token else "[yellow]Will generate[/yellow]")
        console.print(table)
    else:
        print("\nConfiguration Summary:")
        print(f"  App ID: {app_id[:10] + '...' if app_id else 'Not set'}")
        print(f"  App Secret: {'****' if app_secret else 'Not set'}")
        print(f"  Access Token: {'****' if access_token else 'Will generate'}")
    
    if confirm("\nSave this configuration?"):
        env_path = save_env_file(new_config)
        print_success(f"Configuration saved to {env_path}")
        
        # Next steps
        if RICH_AVAILABLE:
            console.print("\n[bold green]Setup Complete![/bold green]\n")
            
            if not access_token:
                console.print("Next step - generate access token:")
                console.print("  [cyan]python get_token.py[/cyan]\n")
            
            console.print("Then test your connection:")
            console.print("  [cyan]python main.py test[/cyan]\n")
            
            console.print("Quick start commands:")
            console.print("  [cyan]python main.py quick[/cyan]      # Fast status")
            console.print("  [cyan]python main.py dashboard[/cyan]  # Web UI")
        else:
            print("\nSetup Complete!\n")
            if not access_token:
                print("Next: python get_token.py")
            print("Test: python main.py test")
    else:
        print("\nSetup cancelled.")


def quick_test():
    """Quick test of current configuration"""
    config = check_env_file()
    
    if RICH_AVAILABLE:
        console.print("\n[bold]Configuration Status:[/bold]\n")
        
        table = Table()
        table.add_column("Setting", style="cyan")
        table.add_column("Status")
        
        table.add_row(
            "Access Token",
            "[green]✓ Set[/green]" if config.get('PINTEREST_ACCESS_TOKEN') else "[red]✗ Missing[/red]"
        )
        table.add_row(
            "App ID",
            "[green]✓ Set[/green]" if config.get('PINTEREST_APP_ID') else "[yellow]○ Optional[/yellow]"
        )
        table.add_row(
            "App Secret",
            "[green]✓ Set[/green]" if config.get('PINTEREST_APP_SECRET') else "[yellow]○ Optional[/yellow]"
        )
        
        console.print(table)
        
        if config.get('PINTEREST_ACCESS_TOKEN'):
            console.print("\n[green]Ready to use![/green] Run: python main.py test")
        else:
            console.print("\n[yellow]Setup required.[/yellow] Run: python setup.py")
    else:
        print("\nConfiguration Status:")
        print(f"  Access Token: {'Set' if config.get('PINTEREST_ACCESS_TOKEN') else 'MISSING'}")
        print(f"  App ID: {'Set' if config.get('PINTEREST_APP_ID') else 'Not set'}")
        print(f"  App Secret: {'Set' if config.get('PINTEREST_APP_SECRET') else 'Not set'}")


if __name__ == '__main__':
    if len(sys.argv) > 1 and sys.argv[1] == 'check':
        quick_test()
    else:
        run_setup_wizard()
